_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./step1_AFI-GAN_training_mask_rcnn_R_50_FPN_1x"
MODEL:
  META_ARCHITECTURE: "SuperResolutionFeature"
  GUIDE_ARCHITECTURE: "RCNN_FPN_only"
  GUIDE_WEIGHTS: "/AFI-GAN/Model_ZOO/Maskrcnn_R50_FPN_x3/model_final_f10217.pkl"
  WEIGHTS: "/AFI-GAN/Model_ZOO/Maskrcnn_R50_FPN_x3/model_final_f10217.pkl"
  AFI_DIS_WEIGHTS: ""
  AFI_GEN_WEIGHTS: ""
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (270000, )
  MAX_ITER: 300000