_BASE_: "../Base-RCNN-FPN-AFIGAN.yaml"
OUTPUT_DIR: "./step2_AF-Extractor_training_mask_rcnn_R_50_FPN_1x"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN_AFExtractor"
  GUIDE_ARCHITECTURE: "RCNN_FPN_only"
  GUIDE_WEIGHTS: "/AFI-GAN/Model_ZOO/Maskrcnn_R50_FPN_x3/model_final_f10217.pkl"
  WEIGHTS: "/AFI-GAN/Model_ZOO/Maskrcnn_R50_FPN_x3/model_final_f10217.pkl"
  AFI_DIS_WEIGHTS: "/AFI-GAN/step1_AFI-GAN_training_mask_rcnn_R_50_FPN_1x/D_0/model_final.pth"
  AFI_GEN_WEIGHTS: "/AFI-GAN/step1_AFI-GAN_training_mask_rcnn_R_50_FPN_1x/G_0/model_final.pth"
  MASK_ON: True
  AFI_FREEZE: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256]]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000